name: build-okd-images
description: Reusable action to build OKD images

inputs:
  ushift-gitref:
    description: MicroShift git ref (branch, tag, commit) from https://github.com/openshift/microshift/branches
    required: true
  okd-version-tag:
    description: OKD version tag from https://quay.io/repository/okd/scos-release?tab=tags
    required: true
  bootc-image-url:
    description: Base Bootc image URL used in `make image` command
    required: false
    default: quay.io/centos-bootc/centos-bootc
  bootc-image-tag:
    description: Base Bootc image tag used in `make image` command
    required: false
    default: stream9
  target-arch:
    description: Target architecture for the OKD images
    required: true
  target-registry:
    description: Target registry for the OKD images
    required: true
  token:
    description: Token for the GitHub Container Registry
    required: true

runs:
  using: "composite"
  steps:
    - name: Detect the CPU architecture
      id: detect-cpu-arch
      uses: ./.github/actions/arch

    - name: Collect debug information before the build
      if: always()
      uses: ./.github/actions/debug-info

    - name: Prepare the build and run environment
      uses: ./.github/actions/prebuild

    - name: Login to GitHub Container Registry
      uses: ./.github/actions/podman-login
      with:
        token: ${{ inputs.token }}

    - name: Build and push OKD images to staging registry
      shell: bash
      run: |
        set -euo pipefail

        cd ${GITHUB_WORKSPACE}/
        # The 'staging' mode builds images locally AND pushes them to staging registry
        # Staging registry is automatically derived as: $(dirname target-registry)/okd-staging
        # This allows testing before promoting to production
        TARGET_REGISTRY="${{ inputs.target-registry }}" ./src/okd/build_images.sh \
          staging \
          "${{ inputs.okd-version-tag }}" \
          "${{ inputs.ushift-gitref }}" \
          "${{ inputs.target-arch }}"

    - name: Build MicroShift RPMs using staging OKD images
      shell: bash
      run: |
        # See https://github.com/microshift-io/microshift/blob/main/docs/build.md
        # for more information about the build process.

        # Run the RPM build process using images from staging registry
        # Staging registry is derived as: $(dirname target-registry)/okd-staging
        cd ${GITHUB_WORKSPACE}/
        PRODUCTION_REGISTRY="${{ inputs.target-registry }}"
        STAGING_REGISTRY="$(dirname "${PRODUCTION_REGISTRY}")/okd-staging"

        # Set the correct architecture-specific variable for staging override
        if [ "${{ inputs.target-arch }}" = "arm64" ]; then
          OKD_OVERRIDE="OKD_RELEASE_IMAGE_AARCH64=${STAGING_REGISTRY}/okd-release-arm64"
        elif [ "${{ inputs.target-arch }}" = "amd64" ]; then
          OKD_OVERRIDE="OKD_RELEASE_IMAGE_X86_64=${STAGING_REGISTRY}/okd-release-amd64"
        else
          echo "ERROR: Unsupported target-arch: ${{ inputs.target-arch }}" ; exit 1
        fi

        make rpm \
          USHIFT_GITREF="${{ inputs.ushift-gitref }}" \
          OKD_VERSION_TAG="${{ inputs.okd-version-tag }}" \
          "${OKD_OVERRIDE}" \
          RPM_OUTDIR=/mnt/rpms

    - name: Build MicroShift bootc container image
      shell: bash
      run: |
        # See https://github.com/microshift-io/microshift/blob/main/docs/build.md
        # for more information about the build process.

        # Run the container image build process.
        cd ${GITHUB_WORKSPACE}/

        make image \
          BOOTC_IMAGE_URL="${{ inputs.bootc-image-url }}" \
          BOOTC_IMAGE_TAG="${{ inputs.bootc-image-tag }}" \

    - name: Run a test to verify that MicroShift is functioning properly
      shell: bash
      run: |
        # See https://github.com/microshift-io/microshift/blob/main/docs/run.md
        # for more information about the run process.

        # Run the MicroShift container
        make run

        # Start-stop test with readiness check
        make run-ready
        make run-healthy
        make stop

    - name: Push OKD images to production registry
      if: success()
      shell: bash
      run: |
        set -euo pipefail

        cd ${GITHUB_WORKSPACE}/
        # Only push to production if all tests passed
        # This ensures we don't publish broken OKD images to production
        TARGET_REGISTRY="${{ inputs.target-registry }}" ./src/okd/build_images.sh \
          production \
          "${{ inputs.okd-version-tag }}" \
          "${{ inputs.ushift-gitref }}" \
          "${{ inputs.target-arch }}"

    # Uncomment this to enable tmate-debug on failure
    # - name: Pause and open tmate debug session
    #   if: failure()
    #   uses: ./.github/actions/tmate-debug

    - name: Collect debug information after the build
      if: always()
      uses: ./.github/actions/debug-info

    - name: Collect MicroShift container sos-report on failure
      if: failure()
      uses: ./.github/actions/sos-report
