name: podman-login
description: Reusable action to login to GitHub Container Registry

inputs:
  token:
    description: Token for the registry
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
        auth_file_path: /tmp/ghcr-auth.json

    - name: Run podman login command
      shell: bash
      run: |
        set -euo pipefail

        sudo chmod 644 /tmp/ghcr-auth.json
        # Login both for the current and elevated users
        podman login      --authfile /tmp/ghcr-auth.json ghcr.io/${{ github.repository_owner }}
        sudo podman login --authfile /tmp/ghcr-auth.json ghcr.io/${{ github.repository_owner }}
