name: podman-login
description: Reusable action to login to a container registry

inputs:
  registry:
    description: Registry to login to
    required: false
    default: ghcr.io
  username:
    description: Username to login with
    required: false
    default: ${{ github.actor }}
  token:
    description: Token for the registry
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to the container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
        auth_file_path: /tmp/registry-auth.json

    - name: Configure podman credentials for elevated privileges
      shell: bash
      run: |
        set -euo pipefail
        set -x

        sudo mkdir -p ~/.config/containers
        sudo cp /tmp/registry-auth.json ~/.config/containers/auth.json
