apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: topolvm-hook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: pvc-hook.topolvm.io
