name: quick-start-clean
description: Reusable action to run the quick start and clean scripts

inputs:
  image-ref:
    description: Image reference to use for the MicroShift container
    required: false
    default: ""
  run-clean:
    description: Run the clean script
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Run the quick start script
      shell: bash
      run: |
        set -euo pipefail
        set -x

        IMAGE=""
        TAG=""
        image_ref="${{ inputs.image-ref }}"
        if [ -n "${image_ref}" ]; then
          IMAGE="${image_ref%%:*}"
          TAG="${image_ref##*:}"
        fi
        sudo IMAGE="${IMAGE}" TAG="${TAG}" bash -xeuo pipefail < ./src/quickstart.sh

        # Wait until the MicroShift service is ready and healthy
        for _ in $(seq 100); do
          state=$(sudo podman exec -i microshift-okd systemctl show --property=SubState --value greenboot-healthcheck 2>/dev/null || echo "unknown")
          if [ "${state}" = "exited" ]; then
            exit 0
          fi
          sleep 10
        done
        exit 1

    - name: Run the quick clean script
      if: ${{ inputs.run-clean == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        set -x
        sudo bash -xeuo pipefail < ./src/quickclean.sh

        # Verify the container and its image are removed
        sudo podman ps -a | grep microshift-okd && exit 1
        sudo podman image exists microshift-okd && exit 1

        # Verify the LVM volume group and backing storage are removed
        VG_NAME="${VG_NAME:-myvg1}"
        sudo vgs | grep "${VG_NAME}" && exit 1
        if [ -e /var/lib/microshift-okd ]; then
          ls -la /var/lib/microshift-okd/
          exit 1
        fi

    # Uncomment this to enable tmate-debug on failure
    # - name: Pause and open tmate debug session
    #   if: failure()
    #   uses: ./.github/actions/tmate-debug

    - name: Collect debug information on failure
      if: failure()
      uses: ./.github/actions/debug-info

    - name: Collect MicroShift container sosreport on failure
      if: failure()
      uses: ./.github/actions/sos-report
