name: detect-okd-version-tag
description: Reusable action to detect the OKD version tag

outputs:
  okd-version-tag:
    description: "OKD Version Tag"
    value: ${{ steps.okd-version-tag.outputs.okd_version_tag }}

runs:
  using: "composite"
  steps:
    - name: Compute the latest OKD version tag
      id: okd-version-tag
      shell: bash
      run: |
        sudo apt-get install -y jq
        # Compute the latest OKD version tag
        okd_version_tag="$(./src/okd/get_version.sh latest)"
        if [ -z "${okd_version_tag}" ]; then
          echo "ERROR: No OKD version tag found"
          exit 1
        fi
        echo "okd_version_tag=${okd_version_tag}" >> $GITHUB_OUTPUT
