name: detect-okd-version-tag
description: Reusable action to detect the latest available OKD version tag

# By default, check the 'arm64' build version availability because it determines
# the latest available OKD version tag for both 'amd64' and 'arm64' architectures.
#
# Checking the latest 'amd64' build version availability is required when building
# a new OKD release for the corresponding version on the 'arm64' architecture.
inputs:
  check-amd64:
    description: "Check the 'amd64' build availability"
    required: false
    default: "false"

outputs:
  okd-version-tag:
    description: "OKD Version Tag"
    value: ${{ steps.okd-version-tag.outputs.okd_version_tag }}

runs:
  using: "composite"
  steps:
    - name: Compute the latest OKD version tag
      id: okd-version-tag
      shell: bash
      run: |
        sudo apt-get install -y jq

        if [ "${{ inputs.check-amd64 }}" = "true" ]; then
          okd_version_tag="$(./src/okd/get_version.sh latest-amd64)"
        else
          okd_version_tag="$(./src/okd/get_version.sh latest-arm64)"
        fi

        if [ -z "${okd_version_tag}" ]; then
          echo "ERROR: No OKD version tag found"
          exit 1
        fi
        echo "okd_version_tag=${okd_version_tag}" >> $GITHUB_OUTPUT
