name: prebuild-environment-setup
description: Reusable action to configure the build environment for MicroShift

runs:
  using: "composite"
  steps:
    - name: Prepare the build and run environment
      shell: bash
      run: |
        set -euo pipefail
        set -x

        # Attempt to clean up any pre-existing files on the /mnt partition to
        # conserve disk space. Note that this is a best-effort approach and
        # not all files may be removed (e.g. swapfile, etc.).
        sudo rm -rvf /mnt/* || true

        # Create the necessary directories on the /mnt partition
        sudo mkdir -p /mnt/tmp /mnt/rpms /mnt/release
        sudo chmod 1777 /mnt/tmp

        # Install the pre-requisites for the build and run environment
        sudo apt-get update  -y -q
        sudo apt-get install -y -q make lvm2 podman jq curl alien

        # Redirect the container build directories to /mnt/ to avoid running out of disk space.
        sudo mv /var/tmp /var/tmp.orig
        sudo mv /var/lib/containers /mnt/containers
        sudo ln -s /mnt/tmp /var/tmp
        sudo ln -s /mnt/containers /var/lib/containers
